# Generated by Django 4.2.2 on 2023-06-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
